In [1]:
import pandas as pd
from matplotlib import pyplot as plt
import numpy as np
import math
import seaborn as sns
import sklearn

%matplotlib inline
sns.set_style('white')
pd.options.display.float_format = '{:.3f}'.format

import datetime

In [2]:

#Loaded csv file into Jupyter and copied column names 

rtbinds = pd.read_csv(r'C:\\Users\\david\\OneDrive\\Documents\\rtbinds.csv', delim_whitespace=False,header=None, names=['pricedate', 'hour', 'cons_name', 'cons_type', 'nercid', 'state',
                                    'shadow', 'mon_fac', 'cont_fac'])

In [3]:
#examining top 5 enteries
rtbinds.head(5)

,pricedate,hour,cons_name,cons_type,nercid,state,shadow,mon_fac,cont_fac
0,5/17/2017 0:00,1,TAHH59MUSFTS,M2M,5223.000,ACTIVATED,0.000,LN TAHLQH5 - HWY59,LN MUSKOGEE - FTSMTH 345 OKGE
1,5/17/2017 0:00,1,TEMP32_22826,FG,22826.000,ACTIVATED,0.000,LN HOBART_J - MARTHA,LN CLINTON4 - WEATHFD 138 WFEC
2,5/17/2017 0:00,1,TEMP86_22813,FG,22813.000,ACTIVATED,0.000,LN ARNOLD2 - RANSOM1,LN MINGO1 - SETAB1 345 SECI
3,5/17/2017 0:00,1,TMP171_22413,FG,22413.000,ACTIVATED,0.000,LN MOORLN1 - CEDRDAL,LN TATONGA - MATHWSN7 345 OKGE
4,5/17/2017 0:00,1,TMP252_22818,FG,22818.000,ACTIVATED,0.000,LN CRKCREEK - CUDAHY1,LN SPERVI1 - MULGRE2 230 SECI

In [4]:
#Making sure all rows are accounted for
rtbinds

,pricedate,hour,cons_name,cons_type,nercid,state,shadow,mon_fac,cont_fac
0,5/17/2017 0:00,1,TAHH59MUSFTS,M2M,5223.000,ACTIVATED,0.000,LN TAHLQH5 - HWY59,LN MUSKOGEE - FTSMTH 345 OKGE
1,5/17/2017 0:00,1,TEMP32_22826,FG,22826.000,ACTIVATED,0.000,LN HOBART_J - MARTHA,LN CLINTON4 - WEATHFD 138 WFEC
2,5/17/2017 0:00,1,TEMP86_22813,FG,22813.000,ACTIVATED,0.000,LN ARNOLD2 - RANSOM1,LN MINGO1 - SETAB1 345 SECI
3,5/17/2017 0:00,1,TMP171_22413,FG,22413.000,ACTIVATED,0.000,LN MOORLN1 - CEDRDAL,LN TATONGA - MATHWSN7 345 OKGE
4,5/17/2017 0:00,1,TMP252_22818,FG,22818.000,ACTIVATED,0.000,LN CRKCREEK - CUDAHY1,LN SPERVI1 - MULGRE2 230 SECI
5,5/17/2017 0:00,1,TEMP88_22478,FG,22478.000,ACTIVATED,0.000,LN NRTHEAST - CROSTOWN,LN IATAN - STRA 345 WR
6,5/17/2017 0:00,1,TMP113_22583,FG,22583.000,ACTIVATED,0.000,LN CIMARRON - DRAPR1,LN ARCAD7 - SEMINOLE 345 OKGE
7,5/17/2017 0:00,1,TMP129_21713,FG,21713.000,ACTIVATED,0.000,XFMR LARAMIE - LARAMIE,BASE
8,5/17/2017 0:00,1,TEMP60_22466,FG,22466.000,ACTIVATED,0.000,LN TUCO - STANTON,LN TUCO - CARLISLE 230 SPS
9,5/17/2017 0:00,1,TMP104_22817,FG,22817.000,ACTIVATED,0.000,LN RB_SPRLK - MOORE_CO,LN HITCH - MOORE_CO 230 SPS
10,5/17/2017 0:00,1,TMP226_22820,FG,22820.000,ACTIVATED,0.000,XFMR FTPECK - FTPECK,LN BELFELD - CHAR_CK 345 WAUE
11,5/17/2017 0:00,1,TMP142_22694,FG,22694.000,ACTIVATED,0.000,LN HOBART_J - MARTHA,LN WHEELER - SWEETWT6 230 CSWS
12,5/17/2017 0:00,1,TMP103_22587,FG,22587.000,ACTIVATED,0.000,LN KILDR - WHEGL,LN HUNTERS7 - WDRNG1 345 OKGE
13,5/17/2017 0:00,1,TEMP46_22719,FG,22719.000,ACTIVATED,0.000,LN NRTHEAST - GRAND_AV,LN NRTHEAST - GA_WEST 161 KCPL
14,5/17/2017 0:00,1,TEMP13_21818,FG,21818.000,BINDING,-25.963,LN PANTEX_S - HIGHL_TP,LN MARTIN - HUTCH 115 SPS
15,5/17/2017 0:00,1,TMP105_22774,FG,22774.000,ACTIVATED,0.000,LN HANSFORD - SPEARMA1,LN HITCH - MOORE_CO 230 SPS
16,5/17/2017 0:00,1,TEMP58_21391,FG,21391.000,BINDING,-181.062,LN WR_SMKHL - SUMM,DBL CLARKCO - THISTLE7 345 SECI
17,5/17/2017 0:00,1,TMP250_22769,FG,22769.000,ACTIVATED,0.000,LN ASPEN - MOORLN1,LN WHEELER - SWEETWT6 230 CSWS
18,5/17/2017 0:00,1,TMP214_22822,FG,22822.000,ACTIVATED,0.000,LN CKSKI1 - KILDR,LN VIOLA7 - WICH 345 WR
19,5/17/2017 0:00,1,TEMP85_22814,FG,22814.000,ACTIVATED,0.000,XFMR WICH - WICH,XF WICH WICH_11 345/138 WR
20,5/17/2017 0:00,1,TEMP87_22823,FG,22823.000,ACTIVATED,0.000,LN BLANCH_S - MAUD_TAP,LN MINCO - CIMARRON 345 OKGE
21,5/17/2017 0:00,1,GAVYANGAVHAR,FG,6569.000,ACTIVATED,0.000,LN GAVINS - YKNTJCT,LN GAVINS - HARTNGTN 115 NPPD
22,5/17/2017 0:00,1,TMP192_21680,FG,21680.000,ACTIVATED,0.000,LN WR_SMKHL - SUMM,LN POSTROCK - AXTELL1 345 NPPD
23,5/17/2017 0:00,1,TMP193_22525,FG,22525.000,ACTIVATED,0.000,LN CRKCREEK - CUDAHY1,LN BUCKNER7 - HOLCOM1 345 SECI
24,5/17/2017 0:00,1,MRTPANHUTMRT,FG,5590.000,ACTIVATED,0.000,LN MARTIN - PANTEX_N,LN MARTIN - HUTCH 115 SPS
25,5/17/2017 0:00,1,PLXSUNTOLYOA,FG,5591.000,ACTIVATED,0.000,LN PLXSUB - SUNDOWN2,LN TOLKSUB - YOAKUM 230 SPS
26,5/17/2017 0:00,1,TMP130_22632,FG,22632.000,ACTIVATED,0.000,LN WHEELER - HOWARD3,LN SWEETWT6 - ELK-CITY 230 CSWS
27,5/17/2017 0:00,1,TMP267_22347,M2M,22347.000,ACTIVATED,0.000,LN ARENDS - FOSTRACB,LN CAYLER - WISDOMCB 161 WAUE
28,5/17/2017 0:00,1,TMP140_22802,FG,22802.000,ACTIVATED,0.000,XFMR COLMBS_E - COLMBS_E,LN SHELLCRK - KELLY 230 NPPD
29,5/17/2017 0:00,1,HOLXFRHOLSET,FG,5026.000,ACTIVATED,0.000,XFMR HOLCOM1 - HOLCOM1,LN HOLCOM1 - SETAB1 345 SECI
...,...,...,...,...,...,...,...,...,...
1048546,4/29/2019 0:00,22,TEMP37_24597,FG,24597.000,ACTIVATED,0.000,LN PETRSBG - ALBION2,LN ANTELOP3-HOSKINS A 345 NPPD
1048547,4/29/2019 0:00,22,WATXFRWATXFR,FG,5579.000,ACTIVATED,0.000,XFMR WATFORD - WATFORD,XF WATFORD KV2A1 230/1 WAUE
1048548,4/29/2019 0:00,23,TEMP48_24759,FG,24759.000,ACTIVATED,0.000,LN FTRANDL - WH_SWAN,LN SIOUXCY-FTRANDL 1 230 WAUE
1048549,4/29/2019 0:00,23,TMP151_24771,FG,24771.000,ACTIVATED,0.000,LN WELSH - DIANA,LN WELSH-WILKES A 345 CSWS
1048550,4/29/2019 0:00,23,TEMP50_23126,FG,23126.000,ACTIVATED,0.000,XFMR POTTER_S - POTTER_S,LN TUCO-BORDER A 345 SPS
1048551,4/29/2019 0:00,23,TEMP89_22229,FG,22229.000,ACTIVATED,0.000,LN GRACMONT - ANADARKO,LN WASHIT1-SW_STA A 138 WFEC
1048552,4/29/2019 0:00,23,TMP175_24736,FG,24736.000,ACTIVATED,0.000,LN CKSKI1 - BRAMAN2,LN HUNTERS7-WDRNG1 A 345 OKGE
1048553,4/29/2019 0:00,23,TMP102_24773,FG,24773.000,ACTIVATED,0.000,LN CONCOR3 - BELOIT3,LN NMAN-ELM_CRK A 230 WR
1048554,4/29/2019 0:00,23,TMP421_24095,FG,24095.000,ACTIVATED,0.000,XFMR CIMARRON - CIMARRON,XF CIMARRON B 345/138 OKGE
1048555,4/29/2019 0:00,23,TMP122_24766,FG,24766.000,ACTIVATED,0.000,LN SUNDOWN2 - SUNDOWN_,TEMP NEEDMORE - YOAKUM 230 KV SPS
1048556,4/29/2019 0:00,23,SPPSPSTIES,FG,5247.000,ACTIVATED,0.000,Multi-Element Constraint,BASE
1048557,4/29/2019 0:00,23,GGS,FG,6006.000,ACTIVATED,0.000,Multi-Element Constraint,BASE
1048558,4/29/2019 0:00,23,BRKXF2BRKXF1,FG,5402.000,ACTIVATED,0.000,XFMR BROOK_LN - BROOK_LN,XF BROOK_LN T1 345/161 AECI
1048559,4/29/2019 0:00,23,TEMP29_23044,FG,23044.000,ACTIVATED,0.000,LN STONEWSW - TUPELO2,LN PITTSB9-VALLIANT A 345 CSWS
1048560,4/29/2019 0:00,23,TMP488_24535,FG,24535.000,ACTIVATED,0.000,XFMR FTTHOMP - FTTHOMP,XF FTTHOMP KU1B1 345/1 WAUE
1048561,4/29/2019 0:00,23,TMP109_22593,FG,22593.000,ACTIVATED,0.000,LN STONEWSW - TUPELO2,LN SEMINOLE-PITTSB9 A 345 OKGE
1048562,4/29/2019 0:00,23,TMP309_24698,FG,24698.000,ACTIVATED,0.000,LN OKEENE1 - DOVERS1,LN CLEOCORNERTAP 138 OKGE
1048563,4/29/2019 0:00,23,TMP294_24287,FG,24287.000,ACTIVATED,0.000,LN WDWRD1 - FPLSWTCH,LN WDWRDEHV-IODINE4 A 138 OKGE
1048564,4/29/2019 0:00,23,TMP268_22624,FG,22624.000,ACTIVATED,0.000,LN HANSFORD - SPEARMA1,XF POTTER_S XF345 345/230 SPS
1048565,4/29/2019 0:00,23,TMP191_24663,FG,24663.000,ACTIVATED,0.000,LN SUNDOWN2 - SUNDOWN_,LN AMOCO_SW-SUNDOWN2 1 230 SPS
1048566,4/29/2019 0:00,23,VINHAYKNOXFR,FG,5406.000,ACTIVATED,0.000,LN VINETAP3 - NHAYS,XF KNOLL1 A 230/115 WR
1048567,4/29/2019 0:00,23,TEMP39_23235,FG,23235.000,ACTIVATED,0.000,LN WAVERLY7 - LACYGNE,LN CAN_RIVR-N345 A 345 WR
1048568,4/29/2019 0:00,23,TEMP71_24753,FG,24753.000,ACTIVATED,0.000,LN KNOLL1 - REDLIN,LN POSTROCK-AXTELL1 A 345 WR
1048569,4/29/2019 0:00,23,CLASHESHEBEA,FG,5634.000,ACTIVATED,0.000,LN CLATONIA - SHELDON,LN SHELDON-BEAPWRST A 115 NPPD
1048570,4/29/2019 0:00,23,TMP195_24770,FG,24770.000,ACTIVATED,0.000,LN CKSKI1 - BRAMAN2,LN MDFRDTP4-RDRUNNR4 A 138 OKGE
1048571,4/29/2019 0:00,23,TAHH59MUSFTS,FG,5223.000,ACTIVATED,0.000,LN TAHLQH5 - HWY59TP,LN MUSKOGEE-FTSMTH A 345 OKGE
1048572,4/29/2019 0:00,23,TMP311_24477,FG,24477.000,ACTIVATED,0.000,LN SPERVI1 - MULGRE2,LN POSTROCK-SPERVI1 A 345 WR
1048573,4/29/2019 0:00,23,TMP235_24734,FG,24734.000,ACTIVATED,0.000,LN ARROWHE2 - CANYON_E,LN DEAFSMIT-BUSHLAND 1 230 SPS
1048574,4/29/2019 0:00,23,TUCXF2TUCXF1,FG,5643.000,ACTIVATED,0.000,XFMR TUCO - TUCO,XF TUCO T2 345/230 SPS
1048575,4/29/2019 0:00,23,TEMP72_22893,FG,22893.000,ACTIVATED,0.000,XFMR WOLF - WOLF,LN WOLF-WAVERLY7 A 345 WR

In [5]:
#curious to see the value counts of each constraint

rtbinds['cons_name'].value_counts()

OSGCANBUSDEA                                       25442
WDWFPLTATNOW                                       25048
GGS                                                22408
SPSNORTH_STH                                       18812
SUNAMOTOLYOA                                       17265
SPPSPSTIES                                         16860
NEORIVNEOBLC                                       14996
PLXSUNTOLYOA                                       12584
WATXFRWATXFR                                       11415
HARPOTHARPOT                                       11372
WODFPLWODXFR                                       11260
SHAHAYPOSKNO                                       11183
HAWXFRHAWXFR                                       10177
CARLPDLUBWOL                                        9970
SMOSUMMULCIR                                        9364
TEMP56_21085                                        9133
VINHAYPOSKNO                                        8759
FRAMIDCANCED                                        8738
BRKXF2BRKXF1                                        8546
TMP228_22196                                        8508
SHAHAYKNOXFR                                        8416
SUNXFRSUNAMO                                        8232
TMP169_21734                                        8146
TEMP94_21410                                        7795
MRTPANHUTMRT                                        7679
TEMP50_20937                                        7473
TEMP60_22466                                        7428
TMP204_21785                                        7264
TMP129_21713                                        6763
TEMP89_22229                                        6666
                                                   ...
WBWL    _TL_HOLLYTL_HOLLY_CHIREA             LN        1
ALLHORFREXFR                                           1
TMP269_23119                                           1
TMP192_24705                                           1
TMP278_24003                                           1
PITECKCLIHOL                                           1
TMP161_24719                                           1
WHEKILWDRHUN                                           1
TEMP51_23488                                           1
STFRA_LUTESV                                           1
TMP263_24727                                           1
TEMP53_22219                                           1
TMP220_24156                                           1
TMP152_21437                                           1
BRKLOUBRKCRK                                           1
TMP204_24415                                           1
TMP132_21088                                           1
NRTGRANRTGAW                                           1
TMP137_20555                                           1
TMP381_24382                                           1
TMP257_22370                                           1
TMP442_24290                                           1
TEMP34_6309                                            1
TMP217_23539                                           1
TMP145_20763                                           1
TMP462_24623                                           1
TEMP27_24105                                           1
TEMP17_21733                                           1
TMP161_22313                                           1
TEMP84_21747                                           1
Name: cons_name, Length: 1795, dtype: int64

In [6]:
#dropping the unecessary columns

rtbinds = rtbinds.drop(['mon_fac','cont_fac','cons_type','nercid','state', 'hour'], axis=1)

In [7]:
#new dataframe with relevant columns

rtbinds

              pricedate     cons_name   shadow
0        5/17/2017 0:00  TAHH59MUSFTS    0.000
1        5/17/2017 0:00  TEMP32_22826    0.000
2        5/17/2017 0:00  TEMP86_22813    0.000
3        5/17/2017 0:00  TMP171_22413    0.000
4        5/17/2017 0:00  TMP252_22818    0.000
5        5/17/2017 0:00  TEMP88_22478    0.000
6        5/17/2017 0:00  TMP113_22583    0.000
7        5/17/2017 0:00  TMP129_21713    0.000
8        5/17/2017 0:00  TEMP60_22466    0.000
9        5/17/2017 0:00  TMP104_22817    0.000
10       5/17/2017 0:00  TMP226_22820    0.000
11       5/17/2017 0:00  TMP142_22694    0.000
12       5/17/2017 0:00  TMP103_22587    0.000
13       5/17/2017 0:00  TEMP46_22719    0.000
14       5/17/2017 0:00  TEMP13_21818  -25.963
15       5/17/2017 0:00  TMP105_22774    0.000
16       5/17/2017 0:00  TEMP58_21391 -181.062
17       5/17/2017 0:00  TMP250_22769    0.000
18       5/17/2017 0:00  TMP214_22822    0.000
19       5/17/2017 0:00  TEMP85_22814    0.000
20       5/17/2017 0:00  TEMP87_22823    0.000
21       5/17/2017 0:00  GAVYANGAVHAR    0.000
22       5/17/2017 0:00  TMP192_21680    0.000
23       5/17/2017 0:00  TMP193_22525    0.000
24       5/17/2017 0:00  MRTPANHUTMRT    0.000
25       5/17/2017 0:00  PLXSUNTOLYOA    0.000
26       5/17/2017 0:00  TMP130_22632    0.000
27       5/17/2017 0:00  TMP267_22347    0.000
28       5/17/2017 0:00  TMP140_22802    0.000
29       5/17/2017 0:00  HOLXFRHOLSET    0.000
...                 ...           ...      ...
1048546  4/29/2019 0:00  TEMP37_24597    0.000
1048547  4/29/2019 0:00  WATXFRWATXFR    0.000
1048548  4/29/2019 0:00  TEMP48_24759    0.000
1048549  4/29/2019 0:00  TMP151_24771    0.000
1048550  4/29/2019 0:00  TEMP50_23126    0.000
1048551  4/29/2019 0:00  TEMP89_22229    0.000
1048552  4/29/2019 0:00  TMP175_24736    0.000
1048553  4/29/2019 0:00  TMP102_24773    0.000
1048554  4/29/2019 0:00  TMP421_24095    0.000
1048555  4/29/2019 0:00  TMP122_24766    0.000
1048556  4/29/2019 0:00    SPPSPSTIES    0.000
1048557  4/29/2019 0:00           GGS    0.000
1048558  4/29/2019 0:00  BRKXF2BRKXF1    0.000
1048559  4/29/2019 0:00  TEMP29_23044    0.000
1048560  4/29/2019 0:00  TMP488_24535    0.000
1048561  4/29/2019 0:00  TMP109_22593    0.000
1048562  4/29/2019 0:00  TMP309_24698    0.000
1048563  4/29/2019 0:00  TMP294_24287    0.000
1048564  4/29/2019 0:00  TMP268_22624    0.000
1048565  4/29/2019 0:00  TMP191_24663    0.000
1048566  4/29/2019 0:00  VINHAYKNOXFR    0.000
1048567  4/29/2019 0:00  TEMP39_23235    0.000
1048568  4/29/2019 0:00  TEMP71_24753    0.000
1048569  4/29/2019 0:00  CLASHESHEBEA    0.000
1048570  4/29/2019 0:00  TMP195_24770    0.000
1048571  4/29/2019 0:00  TAHH59MUSFTS    0.000
1048572  4/29/2019 0:00  TMP311_24477    0.000
1048573  4/29/2019 0:00  TMP235_24734    0.000
1048574  4/29/2019 0:00  TUCXF2TUCXF1    0.000
1048575  4/29/2019 0:00  TEMP72_22893    0.000

[1048576 rows x 3 columns]

In [8]:
#removing the "0:00" string so I can convert the "pricedate" column to datetime

rtbinds['pricedate'] = rtbinds['pricedate'].str.replace('0:00', '')

In [9]:
#Converting to datetime
rtbinds['pricedate'] =  pd.to_datetime(rtbinds['pricedate'])

In [10]:

rtbinds.head(5)

   pricedate     cons_name  shadow
0 2017-05-17  TAHH59MUSFTS   0.000
1 2017-05-17  TEMP32_22826   0.000
2 2017-05-17  TEMP86_22813   0.000
3 2017-05-17  TMP171_22413   0.000
4 2017-05-17  TMP252_22818   0.000

In [11]:
rtbinds.dtypes

pricedate    datetime64[ns]
cons_name            object
shadow              float64
dtype: object

In [12]:
#creating columns for year and week
rtbinds['year'] = rtbinds['pricedate'].apply(lambda x: x.year)
rtbinds['week'] = rtbinds['pricedate'].apply(lambda x: x.isocalendar()[1])

In [13]:
#Creating a new dataframe to grab relevant values
rtbinds2 = rtbinds.groupby(['year', 'week', 'cons_name'], as_index=False).aggregate(np.sum)

In [14]:
#creating a function to present the top 10 values (by sum) of each week

def udf(rtbinds):
    return rtbinds.sort_values('shadow').head(10)

#running function in new df
rtbinds2.groupby(['year', 'week'], as_index=False).apply(udf)

           year  week     cons_name     shadow
0   0      2014     1  BRKXF2BRKXF1  -4567.037
    17     2014     1  TEMP95_20633  -2085.678
    1      2014     1  CBLS56FALGRI  -1861.566
    7      2014     1  OSGCANBUSDEA  -1806.056
    5      2014     1  IATSTRSTJHAW   -445.500
    11     2014     1  SUNAMOTOLYOA   -407.445
    8      2014     1  REDWILLMINGO   -255.240
    6      2014     1  NEORIVNEOBLC   -153.585
    4      2014     1  IATSTRIATEAT    -30.753
    2      2014     1  ELKXFRSWEWHE    -12.908
1   32     2014    34  OSGCANBUSDEA -11461.719
    30     2014    34  NORXFRNORXFR  -5532.811
    53     2014    34  WDWFPLWDWTAT  -4633.636
    52     2014    34  TEMP72_20480  -3837.057
    41     2014    34  TEMP09_20424  -1511.704
    45     2014    34  TEMP43_20311  -1392.831
    51     2014    34  TEMP67_20472  -1142.424
    23     2014    34  GENTLMREDWIL  -1141.616
    33     2014    34  PENMUN87TCRA   -700.000
    34     2014    34  RUSDARANOFTS   -369.519
2   65     2014    35  OSGCANBUSDEA -11264.611
    87     2014    35  TEMP67_20472  -7183.467
    92     2014    35  WDWFPLWDWTAT  -6821.520
    88     2014    35  TEMP72_20480  -4192.937
    85     2014    35  TEMP47_20353  -3227.950
    78     2014    35  TEMP09_20424  -2835.932
    72     2014    35  SHAHAYPOSKNO  -2041.196
    54     2014    35  GENTLMREDWIL  -1932.164
    89     2014    35  TEMP74_20484  -1557.541
    74     2014    35  SMOSUMMULCIR  -1478.619
...         ...   ...           ...        ...
245 13152  2019    16  TMP175_24736 -44859.083
    13129  2019    16  TEMP39_23235 -11907.554
    13145  2019    16  TMP109_22593  -8600.626
    13144  2019    16  TMP106_24492  -7081.045
    13180  2019    16  TMP303_24668  -6125.701
    13149  2019    16  TMP145_24737  -4869.717
    13147  2019    16  TMP127_24687  -3370.589
    13173  2019    16  TMP273_23483  -3281.460
    13137  2019    16  TEMP72_22893  -2981.519
    13193  2019    16  TMP421_24095  -2802.909
246 13260  2019    17  TMP175_24736 -24978.895
    13242  2019    17  TEMP71_24753 -18368.033
    13287  2019    17  TMP303_24668  -6852.938
    13252  2019    17  TMP109_22593  -6728.623
    13313  2019    17  VINHAYKNOXFR  -5265.842
    13223  2019    17  TEMP13_24751  -3357.108
    13276  2019    17  TMP235_24734  -3080.537
    13251  2019    17  TMP106_24492  -2754.874
    13233  2019    17  TEMP48_24759  -2616.833
    13205  2019    17  BRKXF2BRKXF1  -2436.243
247 13329  2019    18  TEMP71_24753  -8198.958
    13339  2019    18  TMP175_24736  -7526.301
    13330  2019    18  TEMP72_22893  -2819.505
    13346  2019    18  TMP273_23483  -1212.934
    13349  2019    18  TMP309_24698  -1069.500
    13321  2019    18  TAHH59MUSFTS   -892.935
    13335  2019    18  TMP109_22593   -387.841
    13331  2019    18  TEMP76_24774   -249.698
    13337  2019    18  TMP147_24775   -204.915
    13325  2019    18  TEMP39_23235   -174.812

[2480 rows x 4 columns]